name: GitHub Pages Pelican Build Action
description: This action builds a Pelican project and deploys it to GitHub Pages.

branding:
  icon: 'home'
  color: 'red'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  GH_PAGES_BRANCH:
    description: 'override the default `gh-pages` deployment branch'
    required: false
    default: 'gh-pages'
  PELICAN_CONFIG_FILE:
    description: 'override the default `pelicanconf.py` config file'
    required: false
    default: pelicanconf.py
